# Introducción a Tensores en PyTorch
<a href="https://colab.research.google.com/github/andrescastro-itm/pytorch_resources/blob/main/1_tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En esta guía se presentan los tensores de PyTorch, sus propiedades y operaciones más comunes.

## ¿Qué son los Tensores?

Los tensores son la estructura de datos fundamental en PyTorch, similar a los arrays de NumPy, pero con capacidades adicionales para computación en GPU y diferenciación automática:

1.  **Aceleración por GPU:** Los tensores pueden ser procesados en GPUs para acelerar significativamente (paralelizar) los cálculos.
2.  **Diferenciación Automática:** El sistema `autograd` de PyTorch puede calcular automáticamente gradientes para tensores, lo que es fundamental para entrenar redes neuronales.

## Importar PyTorch

In [1]:
# Importamos las bibliotecas necesarias
import torch
import numpy as np # Para comparación y conversión

## Creación de tensores

In [2]:
# Creación de tensores desde diferentes fuentes

# 1. Desde una lista
lista = [1, 2, 3, 4]
tensor_desde_lista = torch.tensor(lista)
print("Tensor desde lista:", tensor_desde_lista)

# 2. Desde un array de NumPy
array_numpy = np.array([1, 2, 3, 4])
tensor_desde_numpy = torch.from_numpy(array_numpy)
print("Tensor desde NumPy:", tensor_desde_numpy)

Tensor desde lista: tensor([1, 2, 3, 4])
Tensor desde NumPy: tensor([1, 2, 3, 4], dtype=torch.int32)


## Funciones de Creación de Tensores en PyTorch

PyTorch ofrece múltiples funciones para crear tensores con diferentes inicializaciones como las funciones `ones`, `zeros`, `rand` y `randn`:

In [3]:
# Funciones de creación de tensores

# Tensor de unos
unos = torch.ones(3, 3)
print("Tensor de unos:\n", unos)

# Tensor de ceros
ceros = torch.zeros(2, 4)
print("\nTensor de ceros:\n", ceros)

# Tensor con valores aleatorios
aleatorio = torch.rand(3, 3)  # Distribución uniforme entre 0 y 1
print("\nTensor aleatorio:\n", aleatorio)

# Tensor con valores aleatorios de distribución normal
normal = torch.randn(3, 3)  # Media 0, varianza 1
print("\nTensor de distribución normal:\n", normal)

Tensor de unos:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Tensor de ceros:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Tensor aleatorio:
 tensor([[0.7711, 0.7823, 0.0547],
        [0.7522, 0.2725, 0.8161],
        [0.8402, 0.4639, 0.2485]])

Tensor de distribución normal:
 tensor([[ 1.4524,  0.6204, -0.8149],
        [ 1.0110, -0.3488, -0.0063],
        [ 0.3174,  0.4585, -0.2679]])


## Accediendo a Elementos de un Tensor

Exploraremos diferentes formas de acceder y manipular elementos de tensores:

In [4]:
# Creamos un tensor de ejemplo
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Acceso a elementos individuales
print("Elemento en (0,1):", tensor[0, 1])  # Acceso por índices

# Uso de .item()
# .item() solo funciona con tensores de un solo elemento
tensor_un_elemento = torch.tensor([42])
valor = tensor_un_elemento.item()  # Convierte a valor escalar
print("Valor con .item():", valor)

# NOTA: .item() NO funciona con tensores de múltiples elementos
# Esto generaría un error

Elemento en (0,1): tensor(2)
Valor con .item(): 42


## Ejemplo Práctico

In [5]:
# Crear un tensor 3×4
t = torch.randn(3, 4)
print("dimensión tensor t:", t.shape)

# Reshape → 2×6
t2 = t.view(2, 6)
print("\ndimensión tensor t2:", t2.shape)

# Añadir dimensión extra
t3 = t.unsqueeze(0)    # (1,3,4)
print("\ndimensión tensor t3:", t3.shape)

# Cambiar a GPU
#t_gpu = t.to("cuda")

print("\ntensor en cpu:\n", t)
#print("\ntensor en gpu:\n",t_gpu)

# Operación in-place (sufijo _)
t.add_(10)             # modifica t
print("\nResultado operación in-place:\n", t)

# Clamp (limitar valores)
t.clamp_(min=-1, max=1)
print("\nResultado operación in-place:\n", t)

# Concatenar
a = torch.ones(2, 3)
b = torch.zeros(2, 3)
c = torch.cat([a, b], dim=0)  # (4,3)

print("\ntensor a:\n", a)
print("\ntensor b:\n", b)
print("\ntensor concatenado c:\n", c)

dimensión tensor t: torch.Size([3, 4])

dimensión tensor t2: torch.Size([2, 6])

dimensión tensor t3: torch.Size([1, 3, 4])

tensor en cpu:
 tensor([[ 1.2340, -0.3419, -0.8981,  0.9910],
        [ 0.6305, -0.0516, -3.0774, -1.4162],
        [-1.3995, -0.1550, -0.8788,  0.2988]])

Resultado operación in-place:
 tensor([[11.2340,  9.6581,  9.1019, 10.9910],
        [10.6305,  9.9484,  6.9226,  8.5838],
        [ 8.6005,  9.8450,  9.1212, 10.2988]])

Resultado operación in-place:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor a:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor b:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor concatenado c:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


## Atributo requires_grad y Diferenciación Automática

El atributo `requires_grad` es crucial para el aprendizaje profundo, permitiendo el cálculo automático de gradientes:

In [6]:
# Tensores con seguimiento de gradiente

# Tensor sin seguimiento de gradiente
x = torch.tensor([1.0, 2.0, 3.0])
print("requires_grad por defecto:", x.requires_grad)

# Tensor con seguimiento de gradiente
y = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print("requires_grad activado:", y.requires_grad)

# Ejemplo de cálculo de gradiente
z = y * 2
loss = z.sum()
loss.backward()  # Calcula gradientes

print("\nGradientes de y:", y.grad)

requires_grad por defecto: False
requires_grad activado: True

Gradientes de y: tensor([2., 2., 2.])


## Conclusiones

- Los tensores son la base de los cálculos en PyTorch
- Pueden crearse desde listas, NumPy arrays o funciones específicas
- `requires_grad` permite el seguimiento de operaciones para aprendizaje automático
- `.item()` solo funciona para tensores de un solo elemento