# PyTorch Tensors: The Essentials

This notebook covers the most frequently used concepts, properties, and operations for PyTorch tensors.

## 1. What are Tensors?

At its core, a **PyTorch Tensor** is a multi-dimensional array, very similar to NumPy's `ndarray`. However, Tensors have two key advantages:

1.  **GPU Acceleration:** Tensors can be processed on GPUs to significantly speed up computations.
2.  **Automatic Differentiation:** PyTorch's `autograd` system can automatically compute gradients for tensors, which is fundamental for training neural networks.

## 2. Importing PyTorch

In [1]:
import torch
import numpy as np # For comparison and conversion

## 3. Tensor Creation

Here are some of the most common ways to create tensors:

In [2]:
# From Python lists
data_list = [[1, 2], [3, 4]]
t1 = torch.tensor(data_list)
print("From list:\n", t1)

# From NumPy arrays
data_numpy = np.array([[5., 6.], [7., 8.]])
t2 = torch.tensor(data_numpy) # Copies data
print("\nFrom NumPy array (torch.tensor):\n", t2)

t3 = torch.from_numpy(data_numpy) # Shares memory with numpy array (CPU only)
print("\nFrom NumPy array (torch.from_numpy):\n", t3)

# Tensors of specific values
t_zeros = torch.zeros(2, 3)
print("\nZeros:\n", t_zeros)

t_ones = torch.ones(2, 3)
print("\nOnes:\n", t_ones)

t_fives = torch.full((2,3), 5.0)
print("\nFives:\n", t_fives)

# Tensors with random values
t_rand = torch.rand(2, 3)  # Uniform distribution [0, 1)
print("\nRandom (uniform):\n", t_rand)

t_randn = torch.randn(2, 3) # Standard normal distribution (mean 0, variance 1)
print("\nRandom (normal):\n", t_randn)

# Sequence tensors
t_arange = torch.arange(0, 5, step=1) # Similar to Python's range
print("\nArange:\n", t_arange)

t_linspace = torch.linspace(0, 10, steps=5) # 5 points from 0 to 10
print("\nLinspace:\n", t_linspace)

# `_like` functions (create tensors with same shape/device as another)
t_zeros_like_rand = torch.zeros_like(t_rand)
print("\nZeros like t_rand:\n", t_zeros_like_rand)

From list:
 tensor([[1, 2],
        [3, 4]])

From NumPy array (torch.tensor):
 tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)

From NumPy array (torch.from_numpy):
 tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)

Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Fives:
 tensor([[5., 5., 5.],
        [5., 5., 5.]])

Random (uniform):
 tensor([[0.1325, 0.4052, 0.5916],
        [0.1761, 0.4702, 0.8999]])

Random (normal):
 tensor([[ 0.3144, -0.1433,  1.1871],
        [-1.2651,  0.1509,  0.3956]])

Arange:
 tensor([0, 1, 2, 3, 4])

Linspace:
 tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

Zeros like t_rand:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 4. Tensor Properties (Attributes)

These attributes describe the tensor:

In [3]:
tensor = torch.randn(3, 4)

print("Tensor:\n", tensor)
print("Shape:", tensor.shape)         # Dimensions of the tensor
print("Data type:", tensor.dtype)      # Type of data (e.g., float32, int64)
print("Device:", tensor.device)       # CPU or GPU where tensor is stored
print("Num elements:", tensor.numel()) # Total number of elements

# For autograd (more later)
tensor_grad = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)
print("\nRequires grad:", tensor_grad.requires_grad)

Tensor:
 tensor([[ 1.1582, -1.6811,  1.8171, -1.0014],
        [ 0.0324, -0.1260, -0.1163,  1.0983],
        [-0.0227, -0.7896, -1.0387, -0.9991]])
Shape: torch.Size([3, 4])
Data type: torch.float32
Device: cpu
Num elements: 12

Requires grad: True


## 5. Data Types (`dtype`)

Common data types include `torch.float32` (default for floats), `torch.int64`, `torch.bool`.

In [4]:
t_float32 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print("Float32:", t_float32, t_float32.dtype)

t_int64 = torch.tensor([1, 2, 3], dtype=torch.int64)
print("Int64:", t_int64, t_int64.dtype)

# Convert data type
t_converted_to_float = t_int64.to(torch.float32)
print("Converted to float32:", t_converted_to_float, t_converted_to_float.dtype)

t_converted_to_int = t_float32.to(dtype=torch.int32) # another way to specify
print("Converted to int32:", t_converted_to_int, t_converted_to_int.dtype)

# Shortcut methods
t_short_float = t_int64.float() # equivalent to .to(torch.float32)
print("Shortcut .float():", t_short_float, t_short_float.dtype)

t_short_long = t_float32.long() # equivalent to .to(torch.int64)
print("Shortcut .long():", t_short_long, t_short_long.dtype)

Float32: tensor([1., 2., 3.]) torch.float32
Int64: tensor([1, 2, 3]) torch.int64
Converted to float32: tensor([1., 2., 3.]) torch.float32
Converted to int32: tensor([1, 2, 3], dtype=torch.int32) torch.int32
Shortcut .float(): tensor([1., 2., 3.]) torch.float32
Shortcut .long(): tensor([1, 2, 3]) torch.int64


## 6. Device Management (CPU & GPU)

Tensors can be moved between CPU and GPU.

In [5]:
cpu_tensor = torch.randn(2, 2)
print("CPU Tensor device:", cpu_tensor.device)

# Check if GPU is available
if torch.cuda.is_available():
    print("\nGPU is available!")
    device = torch.device("cuda") # or torch.device("cuda:0") for specific GPU
    
    # Move tensor to GPU
    gpu_tensor = cpu_tensor.to(device)
    print("GPU Tensor device:", gpu_tensor.device)
    
    # Alternative ways to move to GPU
    # gpu_tensor_alt = cpu_tensor.cuda()
    # print("GPU Tensor (alt) device:", gpu_tensor_alt.device)
    
    # Move tensor back to CPU
    cpu_again_tensor = gpu_tensor.to("cpu")
    # cpu_again_tensor_alt = gpu_tensor.cpu()
    print("Back to CPU device:", cpu_again_tensor.device)
    
    # Operations generally require tensors to be on the same device
    try:
        # This would fail if gpu_tensor and cpu_tensor are on different devices
        # result = gpu_tensor + cpu_tensor 
        result_same_device = gpu_tensor + gpu_tensor # This works
        print("Sum on GPU works:", result_same_device.device)
    except RuntimeError as e:
        print("Error operating on tensors on different devices:", e)
else:
    print("\nGPU not available. Skipping GPU examples.")
    device = torch.device("cpu")

CPU Tensor device: cpu

GPU is available!
GPU Tensor device: cuda:0
Back to CPU device: cpu
Sum on GPU works: cuda:0


## 7. Indexing and Slicing

Similar to NumPy arrays.

In [6]:
tensor = torch.arange(12).reshape(3, 4) # 0 to 11, reshaped to 3x4
print("Original Tensor:\n", tensor)

# Get a specific element
print("\nElement at [0, 1]:", tensor[0, 1])

# Get a row
print("First row:", tensor[0, :]) # or tensor[0]

# Get a column
print("Second column:", tensor[:, 1])

# Get a sub-tensor (slice)
print("Sub-tensor (rows 0-1, cols 1-2):\n", tensor[0:2, 1:3])

# Boolean indexing
mask = tensor > 5
print("\nMask (elements > 5):\n", mask)
print("Elements > 5:", tensor[mask])

# Assign a value
tensor_copy = tensor.clone()
tensor_copy[0, 0] = 100
print("\nAfter assignment [0,0]=100:\n", tensor_copy)

Original Tensor:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Element at [0, 1]: tensor(1)
First row: tensor([0, 1, 2, 3])
Second column: tensor([1, 5, 9])
Sub-tensor (rows 0-1, cols 1-2):
 tensor([[1, 2],
        [5, 6]])

Mask (elements > 5):
 tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])
Elements > 5: tensor([ 6,  7,  8,  9, 10, 11])

After assignment [0,0]=100:
 tensor([[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]])


## 8. Reshaping and View Operations

Change the shape of tensors, often without copying data.

In [7]:
x = torch.arange(12) # 0 to 11
print("Original x (1D):", x)

# Reshape (or view)
y = x.reshape(3, 4) # Returns a new tensor (might be a view or copy)
print("\nReshaped to 3x4 (y):\n", y)

z = x.view(3, 4)    # Returns a view (shares data, requires contiguous tensor)
print("Viewed as 3x4 (z):\n", z)
print("z is_contiguous:", z.is_contiguous())

# -1 infers dimension
w = x.reshape(2, -1) # Reshapes to 2x6
print("Reshaped to 2x? (w):\n", w)

# Squeeze (remove dimensions of size 1)
squeezable = torch.randn(1, 3, 1, 2)
print("\nSqueezable (shape {}):\n".format(squeezable.shape), squeezable)
squeezed = squeezable.squeeze()
print("Squeezed (shape {}):\n".format(squeezed.shape), squeezed)

# Unsqueeze (add a dimension of size 1)
unsqueezed = squeezed.unsqueeze(dim=0) # Add dim at the beginning
print("\nUnsqueezed at dim 0 (shape {}):\n".format(unsqueezed.shape), unsqueezed)

# Permute (change order of dimensions)
p = torch.randn(2, 3, 4)
print("\nOriginal p (shape {}):\n".format(p.shape), p)
p_permuted = p.permute(2, 0, 1) # New order: dim 2, then dim 0, then dim 1
print("Permuted p (shape {}):\n".format(p_permuted.shape), p_permuted)

# Transpose (permute for 2D, or swap two specific dims)
mat = torch.randn(2,3)
print("\nOriginal matrix (shape {}):\n".format(mat.shape), mat)
mat_t = mat.t() # or mat.transpose(0,1)
print("Transposed matrix (shape {}):\n".format(mat_t.shape), mat_t)

# Flatten
f = torch.randn(2, 3, 4)
print("\nOriginal f (shape {}):\n".format(f.shape), f)
f_flattened = f.flatten() # Flattens to 1D
print("Flattened f (shape {}):\n".format(f_flattened.shape), f_flattened)
f_flattened_partial = f.flatten(start_dim=1) # Flattens from 2nd dim onwards
print("Partially flattened f (shape {}):\n".format(f_flattened_partial.shape), f_flattened_partial)

Original x (1D): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped to 3x4 (y):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Viewed as 3x4 (z):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
z is_contiguous: True
Reshaped to 2x? (w):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Squeezable (shape torch.Size([1, 3, 1, 2])):
 tensor([[[[ 0.5866, -0.8276]],

         [[-1.0482,  0.2670]],

         [[ 0.9099, -0.6274]]]])
Squeezed (shape torch.Size([3, 2])):
 tensor([[ 0.5866, -0.8276],
        [-1.0482,  0.2670],
        [ 0.9099, -0.6274]])

Unsqueezed at dim 0 (shape torch.Size([1, 3, 2])):
 tensor([[[ 0.5866, -0.8276],
         [-1.0482,  0.2670],
         [ 0.9099, -0.6274]]])

Original p (shape torch.Size([2, 3, 4])):
 tensor([[[ 0.7780, -0.0119,  0.4558, -0.9874],
         [-0.8919, -1.5826, -0.7440, -0.3631],
         [-1.4636,  0.9152,  0.5522,  0.4319]],

        [[ 1.137

## 9. Common Mathematical Operations

In [8]:
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[5., 6.], [7., 8.]])
print("Tensor a:\n", a)
print("Tensor b:\n", b)

# Element-wise operations
print("\nAddition (a + b):\n", a + b) # or torch.add(a, b)
print("Subtraction (a - b):\n", a - b) # or torch.sub(a, b)
print("Multiplication (a * b):\n", a * b) # or torch.mul(a, b)
print("Division (a / b):\n", a / b)   # or torch.div(a, b)
print("Exponentiation (a ** 2):\n", a ** 2) # or torch.pow(a, 2)

print("\nExponential (torch.exp(a)):\n", torch.exp(a))
print("Logarithm (torch.log(a)):\n", torch.log(a))
print("Square root (torch.sqrt(a)):\n", torch.sqrt(a))

# Reduction operations
print("\nSum of all elements in a:", torch.sum(a)) # or a.sum()
print("Mean of all elements in a:", torch.mean(a)) # or a.mean()
print("Max element in a:", torch.max(a))       # or a.max()
print("Min element in a:", torch.min(a))       # or a.min()

# Sum along a dimension
print("Sum along rows (dim=0) of a:", torch.sum(a, dim=0))
print("Sum along columns (dim=1) of a:", torch.sum(a, dim=1))

# Linear algebra: Matrix multiplication
c = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2x3
d = torch.tensor([[7, 8], [9, 10], [11, 12]]) # 3x2
print("\nTensor c (2x3):\n", c)
print("Tensor d (3x2):\n", d)
print("Matrix multiplication (c @ d):\n", c @ d) # or torch.matmul(c, d) or torch.mm(c,d) for 2D

Tensor a:
 tensor([[1., 2.],
        [3., 4.]])
Tensor b:
 tensor([[5., 6.],
        [7., 8.]])

Addition (a + b):
 tensor([[ 6.,  8.],
        [10., 12.]])
Subtraction (a - b):
 tensor([[-4., -4.],
        [-4., -4.]])
Multiplication (a * b):
 tensor([[ 5., 12.],
        [21., 32.]])
Division (a / b):
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
Exponentiation (a ** 2):
 tensor([[ 1.,  4.],
        [ 9., 16.]])

Exponential (torch.exp(a)):
 tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
Logarithm (torch.log(a)):
 tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])
Square root (torch.sqrt(a)):
 tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])

Sum of all elements in a: tensor(10.)
Mean of all elements in a: tensor(2.5000)
Max element in a: tensor(4.)
Min element in a: tensor(1.)
Sum along rows (dim=0) of a: tensor([4., 6.])
Sum along columns (dim=1) of a: tensor([3., 7.])

Tensor c (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor d (3x2):
 tensor([[ 7,  8],

## 10. Broadcasting

Allows operations on tensors of different but compatible shapes.

In [9]:
m = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
v = torch.tensor([10, 20, 30])          # Shape (3,)
print("Matrix m (2x3):\n", m)
print("Vector v (3,):\n", v)

# Add v to each row of m
# v is broadcasted from (3,) to (1, 3) and then to (2, 3)
result = m + v 
print("\nResult of m + v (broadcasting):\n", result)
print("Result shape:", result.shape)

s = torch.tensor([100]) # Scalar as a tensor, shape (1,)
result_scalar = m + s
print("\nResult of m + s (scalar broadcasting):\n", result_scalar)

Matrix m (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Vector v (3,):
 tensor([10, 20, 30])

Result of m + v (broadcasting):
 tensor([[11, 22, 33],
        [14, 25, 36]])
Result shape: torch.Size([2, 3])

Result of m + s (scalar broadcasting):
 tensor([[101, 102, 103],
        [104, 105, 106]])


## 11. Automatic Differentiation (`autograd`)

PyTorch automatically computes gradients, essential for training models.

In [10]:
# Create tensors that require gradient tracking
x_val = torch.tensor(2.0, requires_grad=True)
w_val = torch.tensor(3.0, requires_grad=True)
b_val = torch.tensor(1.0, requires_grad=True)

# Define a simple computation (forward pass)
y_val = w_val * x_val + b_val  # y = 3*2 + 1 = 7

# Compute gradients (backward pass)
# This computes dy/dx, dy/dw, dy/db
y_val.backward()

print("y_val:", y_val)
print("Gradient of y w.r.t. x_val (dy/dx):", x_val.grad) # Should be w_val = 3
print("Gradient of y w.r.t. w_val (dy/dw):", w_val.grad) # Should be x_val = 2
print("Gradient of y w.r.t. b_val (dy/db):", b_val.grad) # Should be 1

# Gradients are accumulated. For training loops, zero them out.
# Example: if you had an optimizer `opt`
# opt.zero_grad() # before calling loss.backward()

# Disabling gradient tracking (e.g., for inference)
with torch.no_grad():
    y_no_grad = w_val * x_val + b_val
    print("\nOutput with no_grad:", y_no_grad)
    print("y_no_grad.requires_grad:", y_no_grad.requires_grad)

# Detaching a tensor from the computation graph
detached_y = y_val.detach()
print("\nDetached y:", detached_y)
print("detached_y.requires_grad:", detached_y.requires_grad)

y_val: tensor(7., grad_fn=<AddBackward0>)
Gradient of y w.r.t. x_val (dy/dx): tensor(3.)
Gradient of y w.r.t. w_val (dy/dw): tensor(2.)
Gradient of y w.r.t. b_val (dy/db): tensor(1.)

Output with no_grad: tensor(7.)
y_no_grad.requires_grad: False

Detached y: tensor(7.)
detached_y.requires_grad: False


## 12. NumPy Bridge

Converting between PyTorch Tensors and NumPy arrays.

In [11]:
# Tensor to NumPy array
cpu_t = torch.ones(5)         # Must be on CPU
np_arr = cpu_t.numpy()        # Shares memory
print("Original tensor:", cpu_t)
print("NumPy array:", np_arr)

cpu_t.add_(1) # In-place addition to tensor
print("\nTensor after add_(1):", cpu_t)
print("NumPy array after tensor modification:", np_arr) # NumPy array also changes

# NumPy array to Tensor
np_arr_2 = np.array([1, 2, 3, 4, 5])
torch_t_2 = torch.from_numpy(np_arr_2) # Shares memory
print("\nOriginal NumPy array:", np_arr_2)
print("Torch tensor from NumPy:", torch_t_2)

np.add(np_arr_2, 1, out=np_arr_2) # In-place addition to NumPy array
print("\nNumPy array after add:", np_arr_2)
print("Torch tensor after NumPy modification:", torch_t_2) # Tensor also changes

# If you want a copy instead of sharing memory, use torch.tensor()
torch_t_copy = torch.tensor(np_arr_2)
np.add(np_arr_2, 10, out=np_arr_2)
print("\nNumPy array after 2nd add:", np_arr_2)
print("Torch tensor copy (unaffected):", torch_t_copy)

Original tensor: tensor([1., 1., 1., 1., 1.])
NumPy array: [1. 1. 1. 1. 1.]

Tensor after add_(1): tensor([2., 2., 2., 2., 2.])
NumPy array after tensor modification: [2. 2. 2. 2. 2.]

Original NumPy array: [1 2 3 4 5]
Torch tensor from NumPy: tensor([1, 2, 3, 4, 5])

NumPy array after add: [2 3 4 5 6]
Torch tensor after NumPy modification: tensor([2, 3, 4, 5, 6])

NumPy array after 2nd add: [12 13 14 15 16]
Torch tensor copy (unaffected): tensor([2, 3, 4, 5, 6])


## End of Essentials

This covers many of the fundamental and most-used aspects of PyTorch tensors. For more advanced topics, refer to the official PyTorch documentation.