# Introducción a Tensores en PyTorch 

En esta guía se presentan los tensores de PyTorch, sus propiedades y operaciones más comunes.

## ¿Qué son los Tensores?

Los tensores son la estructura de datos fundamental en PyTorch, similar a los arrays de NumPy, pero con capacidades adicionales para computación en GPU y diferenciación automática:

1.  **Aceleración por GPU:** Los tensores pueden ser procesados en GPUs para acelerar significativamente (paralelizar) los cálculos.
2.  **Diferenciación Automática:** El sistema `autograd` de PyTorch puede calcular automáticamente gradientes para tensores, lo que es fundamental para entrenar redes neuronales.

## Importar PyTorch

In [1]:
# Importamos las bibliotecas necesarias
import torch
import numpy as np # Para comparación y conversión

## Creación de tensores

In [2]:
# Creación de tensores desde diferentes fuentes

# 1. Desde una lista
lista = [1, 2, 3, 4]
tensor_desde_lista = torch.tensor(lista)
print("Tensor desde lista:", tensor_desde_lista)

# 2. Desde un array de NumPy
array_numpy = np.array([1, 2, 3, 4])
tensor_desde_numpy = torch.from_numpy(array_numpy)
print("Tensor desde NumPy:", tensor_desde_numpy)

Tensor desde lista: tensor([1, 2, 3, 4])
Tensor desde NumPy: tensor([1, 2, 3, 4])


## Funciones de Creación de Tensores en PyTorch

PyTorch ofrece múltiples funciones para crear tensores con diferentes inicializaciones como las funciones `ones`, `zeros`, `rand` y `randn`:

In [3]:
# Funciones de creación de tensores

# Tensor de unos
unos = torch.ones(3, 3)
print("Tensor de unos:\n", unos)

# Tensor de ceros
ceros = torch.zeros(2, 4)
print("\nTensor de ceros:\n", ceros)

# Tensor con valores aleatorios
aleatorio = torch.rand(3, 3)  # Distribución uniforme entre 0 y 1
print("\nTensor aleatorio:\n", aleatorio)

# Tensor con valores aleatorios de distribución normal
normal = torch.randn(3, 3)  # Media 0, varianza 1
print("\nTensor de distribución normal:\n", normal)

Tensor de unos:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Tensor de ceros:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Tensor aleatorio:
 tensor([[0.0126, 0.0166, 0.7048],
        [0.7827, 0.4718, 0.3158],
        [0.4028, 0.8378, 0.2972]])

Tensor de distribución normal:
 tensor([[-0.3977,  1.1284,  0.4420],
        [ 0.4918,  1.2484, -0.1590],
        [ 0.9218, -0.2033, -0.0228]])


## Accediendo a Elementos de un Tensor

Exploraremos diferentes formas de acceder y manipular elementos de tensores:

In [4]:
# Creamos un tensor de ejemplo
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Acceso a elementos individuales
print("Elemento en (0,1):", tensor[0, 1])  # Acceso por índices

# Uso de .item()
# .item() solo funciona con tensores de un solo elemento
tensor_un_elemento = torch.tensor([42])
valor = tensor_un_elemento.item()  # Convierte a valor escalar
print("\nValor con .item():", valor)

# NOTA: .item() NO funciona con tensores de múltiples elementos
# Esto generaría un error

Elemento en (0,1): tensor(2)

Valor con .item(): 42


## Atributo requires_grad y Diferenciación Automática

El atributo `requires_grad` es crucial para el aprendizaje profundo, permitiendo el cálculo automático de gradientes:

In [5]:
# Tensores con seguimiento de gradiente

# Tensor sin seguimiento de gradiente
x = torch.tensor([1.0, 2.0, 3.0])
print("requires_grad por defecto:", x.requires_grad)

# Tensor con seguimiento de gradiente
y = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print("requires_grad activado:", y.requires_grad)

# Ejemplo de cálculo de gradiente
z = y * 2
loss = z.sum()
loss.backward()  # Calcula gradientes

print("\nGradientes de y:", y.grad)

requires_grad por defecto: False
requires_grad activado: True

Gradientes de y: tensor([2., 2., 2.])


## Conclusiones

- Los tensores son la base de los cálculos en PyTorch
- Pueden crearse desde listas, NumPy arrays o funciones específicas
- `requires_grad` permite el seguimiento de operaciones para aprendizaje automático
- `.item()` solo funciona para tensores de un solo elemento